refactor: styles cleanup, theming, tooling update
tem-tem/shortcuts pull request #1
Opened 2022-12-26 22:26 UTC by nlozgachev

2022-12-26 22:49 UTC, tem-tem requested changes
спасибо за помощь, как раз не понимал как лучше подойти к темам и просто на коленке сделал чето
там что то сломано, я добавил коммент

2022-12-26 22:49 UTC, tem-tem commented on src/utils/themeToCSSVariables.ts
> +export const themeToCSSVariables = (theme: ThemeColors) => {
он как то странно добавляет цвета, так задумано? у меня тема перестает меняться, после нескольких кликов на одну тему
 
<img width="403" alt="image" src="https://user-images.githubusercontent.com/18738841/209586922-2e00466c-64d1-4456-b6e7-b7e5669aee47.png">

1 клик на тему работает нормально:
<img width="361" alt="image" src="https://user-images.githubusercontent.com/18738841/209586994-0b4c32a2-1708-4ab0-b32a-045e628ed341.png">

2022-12-26 22:49 UTC, tem-tem commented on src/routes/+page.svelte
>  	footer {
футеру нужен width: 100%, иначе он не приравнен к "невидимым стенам"

<img width="911" alt="image" src="https://user-images.githubusercontent.com/18738841/209587052-d389d70b-6ba8-418a-8cfc-c69e712d53a1.png">

2022-12-26 22:49 UTC, tem-tem commented on src/routes/+page.svelte
> +			<!-- <div /> -->
видимо я забыл удалить, убери пожалуйста

2022-12-27 16:04 UTC, nlozgachev commented on src/utils/themeToCSSVariables.ts
> +export const themeToCSSVariables = (theme: ThemeColors) => {
:heavy_check_mark: 

Переборщил с мутациями. Теперь всё ок.

2022-12-27 16:04 UTC, nlozgachev commented on src/routes/+page.svelte
>  	footer {
:heavy_check_mark:

2022-12-27 16:04 UTC, nlozgachev commented on src/routes/+page.svelte
> +			<!-- <div /> -->
:heavy_check_mark:

2022-12-27 19:42 UTC, tem-tem requested changes

2022-12-27 19:42 UTC, tem-tem commented on src/components/Theme.svelte
> +			browser && JSON.parse(JSON.stringify(localStorage.getItem('defaultTheme')) ?? '');
не понимаю зачем здесь нужен stringify а затем parse?

2022-12-27 19:42 UTC, tem-tem commented on src/components/Theme.svelte
> +			browser && JSON.parse(JSON.stringify(localStorage.getItem('defaultTheme')) ?? '');
предлагаю избегать длинных строк, чтобы быстрее читать код

2022-12-27 19:42 UTC, tem-tem commented on src/components/Theme.svelte
> +			browser && JSON.parse(JSON.stringify(localStorage.getItem('defaultTheme')) ?? '');
`savedTheme` это название темы, а не сама тема? давай исправим на `savedThemeName`

а еще это я дал название `defaultTheme`, но мне кажется оно не подходит для переменной, которая хранит выбор пользователя, плюс с твоими изменениями там просто название темы

есть предложения для более подходящего названия?  userThemeName, savedThemeName?

2022-12-27 19:42 UTC, tem-tem commented on src/components/Theme.svelte
> +	const themeNameTypes = Object.keys(themes) as ThemeName[];
достаточно просто themeNames, или Types что то означает?

2022-12-27 19:42 UTC, tem-tem commented on src/components/Theme.svelte
> +	let localThemeName: ThemeName;
в этом же файле идёт работа с localStorage, поэтому  `localThemeName` моментами путает понимание

2022-12-27 19:42 UTC, tem-tem commented on src/routes/+page.svelte
> +			<a href="https://github.com/Sergushka">Aleksander</a>
```suggestion
		2022 | Made by <a href="https://github.com/tem-tem">Tem</a><br />
		Contributors: <a href="https://github.com/Sergushka">Aleksander</a>, <a href="https://github.com/nlozgachev">Nikita</a>
```

2022-12-27 19:42 UTC, tem-tem commented on src/data/themes.ts
> +export const themes: Record<ThemeName, ThemeColors> = {
переименуем в themeColros? 

`theme` это название темы (src/stores/theme.ts), а здесь `themes` это не список названий, а объекты с цветами

2022-12-27 19:42 UTC, tem-tem commented on src/types/index.ts
> +export type CSSVarName = `--main-${ColorNames}-color`;
ебать не знал что так можно

2022-12-27 19:42 UTC, tem-tem commented on src/utils/themeToCSSVariables.ts
> +};
предлагаю выделять блоки в отдельные методы, вместо комментов

```suggestion
import type { CSSVarName, CSSVariables, ThemeColors, ThemeName } from '$types';
import { themes } from '$data/themes';

export const themeToCSSVariables = (themeName: ThemeName): string => {
	const themeColors = themes[themeName];

	const cssVars = getCSSVarsFromThemeColors(themeColors)
	return constructCSSVarsString(cssVars);
};

const getCSSVarsFromThemeColors = (colors: ThemeColors): CSSVariables => {
	const colorKeys = Object.keys(colors) as [keyof ThemeColors];
	const cssVars = colorKeys.reduce((prev, color) => {
		prev[`--main-${color}-color`] = colors[color];
		return prev;
	}, {} as CSSVariables);
	return cssVars;
};

const constructCSSVarsString = (cssVars: CSSVariables): string => {
	const cssVarsKeys = Object.keys(cssVars) as CSSVarName[];
	return cssVarsKeys.reduce((prev, curr) => prev.concat(`${curr}:${cssVars[curr]};\n`), '');
};
```

2022-12-27 22:02 UTC, nlozgachev commented on src/data/themes.ts
> +export const themes: Record<ThemeName, ThemeColors> = {
> themeColors
- это hex/rgb/hsl значения цветов? 
- насколько глубока кроличья нора этого объекта? Там лежат цвета какой-то конкретной темы?

При таком подходе слишком много времени уходит на придумывание "наиболее точных" с субъективной точки зрения названий и слишком мало на работу :smiley_cat:

2022-12-27 22:03 UTC, nlozgachev commented on src/components/Theme.svelte
> +			browser && JSON.parse(JSON.stringify(localStorage.getItem('defaultTheme')) ?? '');
> не понимаю зачем здесь нужен stringify а затем parse?

А он там и не нужен, забыл убрать после перехода от хранения всей темы в LS.

---
> savedTheme это название темы, а не сама тема? давай исправим на savedThemeName

- Добавляем слово, больше букв, смысл тот же. Сейчас нечто короткое и контекста ясно, что там лежит.
- Изменение функционала с хранения объекта темы на её имя соответственно поменяло и "парадигму" работы со всеми связанными частями. Обязательно ли так подходить к неймингу, если из логики понятно, как эта часть работает?

---

> есть предложения для более подходящего названия? userThemeName, savedThemeName?

Философские мучения с неймингом ключа в localStorage действительно стоят потраченного времени, или я что-то упускаю?
У github переменная с названием `preferred_color_mode` такое хранит например. (замечу, не `preferred_color_mode_name` )

2022-12-27 23:37 UTC, tem-tem commented on src/components/Theme.svelte
> +			browser && JSON.parse(JSON.stringify(localStorage.getItem('defaultTheme')) ?? '');
согласен, сейчас достаточно контекста, потом ситуация может изменится или может не измениться совсем. В худшем случае будет код, который легче понять не сильно вникая в контекст.

Названия должны соответствовать своему смыслу. Они в принципе нужны чтобы быть якорем при чтении кода, чтобы не приходилось/помогало вникать в логику. Иначе, мы могли бы обойтись просто одной-двумя буквами. Хороший нейминг помогает быстрее читать код, поэтому эта работа стоит потраченного времени

preferredTheme - давай выберем этот

тогда в целом, давай остановимся на том, что `theme` будет означать название темы
а вот themes в [src/data/themes.ts](https://github.com/tem-tem/shortcuts/pull/1/files/b11e91cbf2b8add86712c655d69e21d0f4dbbae5#diff-6a6577c11094fc48609b348259ef3f274ed9d9b80d5769da181db53c5bda2639) нужно переименовать в `themeColors`

2023-01-01 13:12 UTC, nlozgachev commented on src/routes/+page.svelte
> +			<a href="https://github.com/Sergushka">Aleksander</a>
![image](https://user-images.githubusercontent.com/31391652/210171682-23187876-bc3d-4c02-9a4e-3ecc956c8582.png)

2023-01-04 14:43 UTC, tem-tem approved these changes

2023-01-04 14:43 UTC, tem-tem commented on src/routes/+page.svelte
> +			<a href="https://github.com/Sergushka">Aleksander</a>
ок, соре 😭

2023-01-04 14:45 UTC, tem-tem commented
@nlozgachev спасибо огромное!!

2023-01-04 14:47 UTC, merged